# Generated by Django 2.0.6 on 2018-09-08 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id_atm', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('no_cuenta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('beneficiario', models.CharField(max_length=50)),
                ('saldo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.BigIntegerField()),
                ('tipo', models.CharField(max_length=10)),
                ('importe', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('banco', models.CharField(max_length=100)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmPostService.Cuenta')),
                ('id_atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmPostService.Cajero')),
            ],
        ),
    ]
