# Generated by Django 2.0.6 on 2018-09-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmPostService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajero',
            name='ubicacion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
