# Generated by Django 2.0.6 on 2018-09-08 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atmPostService', '0002_cajero_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='eCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecode', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='transaccion',
            name='id_transaccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cuenta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='ecode',
            name='id_transaccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atmPostService.Transaccion'),
        ),
    ]
