# Generated by Django 2.0.6 on 2018-09-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmPostService', '0003_auto_20180908_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecode',
            name='fecha_uso',
            field=models.DateTimeField(null=True),
        ),
    ]
