# Generated by Django 2.0.6 on 2018-09-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmPostService', '0004_ecode_fecha_uso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='id',
        ),
        migrations.AlterField(
            model_name='ecode',
            name='fecha_uso',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_transaccion',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
