# Generated by Django 2.0.6 on 2018-09-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmPostService', '0006_auto_20180909_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecode',
            name='id_trans',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
